#Database
DB_USERNAME: root
DB_PASSWORD: Xn978541
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: thevergov_db

#Server
CONTAINER_PORT: 8080
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: vergovmiroslav@gmail.com
EMAIL_PASSWORD: Xn978541
VERIFY_EMAIL_HOST: http://localhost:8080